# Form implementation generated from reading ui file './ui_raw/open_Brower.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OpenBrower(object):
    def setupUi(self, OpenBrower):
        OpenBrower.setObjectName("OpenBrower")
        OpenBrower.resize(510, 165)
        self.verticalLayout = QtWidgets.QVBoxLayout(OpenBrower)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(OpenBrower)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_input = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_input.setFont(font)
        self.lineEdit_input.setInputMask("")
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.verticalLayout_2.addWidget(self.lineEdit_input)
        self.checkBox_get_from_db = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_get_from_db.setObjectName("checkBox_get_from_db")
        self.verticalLayout_2.addWidget(self.checkBox_get_from_db)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_open = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_open.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButton_open.setObjectName("pushButton_open")
        self.horizontalLayout.addWidget(self.pushButton_open)
        self.pushButton_update = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_update.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButton_update.setObjectName("pushButton_update")
        self.horizontalLayout.addWidget(self.pushButton_update)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(OpenBrower)
        QtCore.QMetaObject.connectSlotsByName(OpenBrower)

    def retranslateUi(self, OpenBrower):
        _translate = QtCore.QCoreApplication.translate
        OpenBrower.setWindowTitle(_translate("OpenBrower", "Open Brower"))
        self.groupBox.setTitle(_translate("OpenBrower", "Proxy"))
        self.lineEdit_input.setPlaceholderText(_translate("OpenBrower", "IP:PORT:USER_NAME:PASSWORD"))
        self.checkBox_get_from_db.setText(_translate("OpenBrower", "Get proxy from DB"))
        self.pushButton_open.setText(_translate("OpenBrower", "Open"))
        self.pushButton_update.setText(_translate("OpenBrower", "Update"))
